language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
