language: php
dist: precise
sudo: required

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
before_script:
  - composer require satooshi/php-coveralls:dev-master
  - composer install --dev
script:
  - vendor/bin/phpunit
after_script:
  - php vendor/bin/coveralls -v
