language: php
dist: trusty

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: UPDATE_COVERAGE=1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true
script:
  - ./build.sh
